CREATE SCHEMA TaskManager

GO

CREATE TABLE TaskManager.Task
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    TaskName NVARCHAR(1000) NOT NULL,
    DueDate DATETIME NULL, 
    CreatedBy NVARCHAR(25) NOT NULL, 
    CreatedDate DATETIME  NOT NULL,
    ModifiedBy NVARCHAR(25) NOT NULL,
    ModifiedDate DATETIME NOT NULL
)

GO

CREATE TABLE TaskManager.Category
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    CategoryName NVARCHAR(50) NOT NULL, 
    CreatedBy NVARCHAR(25) NOT NULL, 
    CreatedDate DATETIME  NOT NULL,
    ModifiedBy NVARCHAR(25) NOT NULL,
    ModifiedDate DATETIME NOT NULL
)

GO

CREATE TABLE TaskManager.TaskCategory
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CategoryId INT NOT NULL,
    TaskId INT NOT NULL,
    CONSTRAINT FK_TASKCATEGORY_TASK FOREIGN KEY (TaskId)
    REFERENCES TASKMANAGER.TASK(Id),
    CONSTRAINT FK_TASKCATEGORY_CATEGORY FOREIGN KEY (CategoryId)
    REFERENCES TASKMANAGER.Category(Id),
)

GO

--CREATE TABLE TASKMANAGER.USER
