CREATE SCHEMA TaskManager

GO

CREATE TABLE TaskManager.Task
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    TaskName NVARCHAR(1000) NOT NULL,
    DueDate DATETIME NULL, 
    IsCompleted BIT NOT NULL DEFAULT 0,
    CreatedBy NVARCHAR(25) NOT NULL, 
    CreatedDate DATETIME  NOT NULL,
    ModifiedBy NVARCHAR(25),
    ModifiedDate DATETIME
)

GO

CREATE TABLE TaskManager.Category
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    CategoryName NVARCHAR(50) NOT NULL, 
    CreatedBy NVARCHAR(25) NOT NULL, 
    CreatedDate DATETIME  NOT NULL,
    ModifiedBy NVARCHAR(25),
    ModifiedDate DATETIME
)

GO

CREATE TABLE TaskManager.TaskCategory
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CategoryId INT NOT NULL,
    TaskId INT NOT NULL,
    CreatedBy NVARCHAR(25) NOT NULL, 
    CreatedDate DATETIME  NOT NULL,
    ModifiedBy NVARCHAR(25),
    ModifiedDate DATETIME
    CONSTRAINT FK_TASKCATEGORY_TASK FOREIGN KEY (TaskId)
    REFERENCES TASKMANAGER.TASK(Id),
    CONSTRAINT FK_TASKCATEGORY_CATEGORY FOREIGN KEY (CategoryId)
    REFERENCES TASKMANAGER.Category(Id),
)

GO

--CREATE TABLE TASKMANAGER.USER
CREATE TABLE [TaskManager].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserEmail] [nvarchar](255) NOT NULL,
    [Name] [nvarchar](255) NOT NULL,
    [CreatedBy] NVARCHAR(25) NOT NULL, 
    [CreatedDate] DATETIME  NOT NULL,
    [ModifiedBy] NVARCHAR(25),
    [ModifiedDate] DATETIME
) ON [PRIMARY]
GO
